import { Poppins } from "next/font/google";
import "./globals.css";

const poppins = Poppins({
  variable: "--font-poppins", // ✅ use correct variable name
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"], // add weights you need
});

export const metadata = {
  title: "Tahmina | Portfolio",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${poppins.className} antialiased`}>
        {children}
      </body>
    </html>
  );
}
